### ISSUE TITLE
Separate CSS from JS

### ISSUE THREAD

**Issue by scherii** [clubdesign/floatlabels.js#14]
Thank you for your work! :)

It would be great if the script would not use inline styles so you could customize it with CSS.

My suggestion:
Instead of inline styles you could apply classes.
Default styles could be provided with a separate floatlabels.css.

**Comment by clubdesign** [comment]
As soon as i have time again, i will fix that.

**Comment by simonberger** [comment]
Done here: https://github.com/simonberger/floatlabels.js/commit/6ffd484fb3341bdbc375c43b42553fbe626b5a9b

**Comment by agquick** [comment]
+1 Using inline style makes the label unnecessarily more difficult to tweak. Will try fix by simonberger. I'd even be ok with just being able to pass in my own css style hash to the options.
